export const platformAssets = [
  {
    asset: "agentswarm-darwin-arm64",
    source: "@vrsen/agentswarm-cli-darwin-arm64",
    target: "@vrsen/openswarm-cli-darwin-arm64",
    os: "darwin",
    cpu: "arm64",
    binary: "agentswarm",
  },
  {
    asset: "agentswarm-darwin-x64",
    source: "@vrsen/agentswarm-cli-darwin-x64",
    target: "@vrsen/openswarm-cli-darwin-x64",
    os: "darwin",
    cpu: "x64",
    binary: "agentswarm",
  },
  {
    asset: "agentswarm-darwin-x64-baseline",
    source: "@vrsen/agentswarm-cli-darwin-x64-baseline",
    target: "@vrsen/openswarm-cli-darwin-x64-baseline",
    os: "darwin",
    cpu: "x64",
    binary: "agentswarm",
  },
  {
    asset: "agentswarm-linux-arm64",
    source: "@vrsen/agentswarm-cli-linux-arm64",
    target: "@vrsen/openswarm-cli-linux-arm64",
    os: "linux",
    cpu: "arm64",
    binary: "agentswarm",
  },
  {
    asset: "agentswarm-linux-arm64-musl",
    source: "@vrsen/agentswarm-cli-linux-arm64-musl",
    target: "@vrsen/openswarm-cli-linux-arm64-musl",
    os: "linux",
    cpu: "arm64",
    binary: "agentswarm",
  },
  {
    asset: "agentswarm-linux-x64",
    source: "@vrsen/agentswarm-cli-linux-x64",
    target: "@vrsen/openswarm-cli-linux-x64",
    os: "linux",
    cpu: "x64",
    binary: "agentswarm",
  },
  {
    asset: "agentswarm-linux-x64-baseline",
    source: "@vrsen/agentswarm-cli-linux-x64-baseline",
    target: "@vrsen/openswarm-cli-linux-x64-baseline",
    os: "linux",
    cpu: "x64",
    binary: "agentswarm",
  },
  {
    asset: "agentswarm-linux-x64-baseline-musl",
    source: "@vrsen/agentswarm-cli-linux-x64-baseline-musl",
    target: "@vrsen/openswarm-cli-linux-x64-baseline-musl",
    os: "linux",
    cpu: "x64",
    binary: "agentswarm",
  },
  {
    asset: "agentswarm-linux-x64-musl",
    source: "@vrsen/agentswarm-cli-linux-x64-musl",
    target: "@vrsen/openswarm-cli-linux-x64-musl",
    os: "linux",
    cpu: "x64",
    binary: "agentswarm",
  },
  {
    asset: "agentswarm-windows-arm64.exe",
    source: "@vrsen/agentswarm-cli-windows-arm64",
    target: "@vrsen/openswarm-cli-windows-arm64",
    os: "win32",
    cpu: "arm64",
    binary: "agentswarm.exe",
  },
  {
    asset: "agentswarm-windows-x64.exe",
    source: "@vrsen/agentswarm-cli-windows-x64",
    target: "@vrsen/openswarm-cli-windows-x64",
    os: "win32",
    cpu: "x64",
    binary: "agentswarm.exe",
  },
  {
    asset: "agentswarm-windows-x64-baseline.exe",
    source: "@vrsen/agentswarm-cli-windows-x64-baseline",
    target: "@vrsen/openswarm-cli-windows-x64-baseline",
    os: "win32",
    cpu: "x64",
    binary: "agentswarm.exe",
  },
]
